"""Create currency table

Revision ID: 1e92c5f09564
Revises: 
Create Date: 2024-02-21 12:40:31.713280

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e92c5f09564"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currency_code"), "currency", ["code"], unique=True)
    op.create_table(
        "currency_rate",
        sa.Column("currency_code_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_code_id"],
            ["currency.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_currency_rate_currency_code_id"),
        "currency_rate",
        ["currency_code_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currency_rate_currency_code_id"), table_name="currency_rate")
    op.drop_table("currency_rate")
    op.drop_index(op.f("ix_currency_code"), table_name="currency")
    op.drop_table("currency")
    # ### end Alembic commands ###
