"""Create currency tables

Revision ID: 2166600e619b
Revises: 
Create Date: 2024-02-21 20:13:11.382023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2166600e619b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencyrates",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currencyrates_code"), "currencyrates", ["code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currencyrates_code"), table_name="currencyrates")
    op.drop_table("currencyrates")
    # ### end Alembic commands ###
